import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — LexLens',
  description: 'Terms of Service for LexLens AI Contract Analyzer.',
};

const LAST_UPDATED = 'June 17, 2026';

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16 text-[#CBD5E1]">
      <h1 className="text-4xl font-bold text-[#F8FAFC] mb-2" style={{ fontFamily: 'Syne, sans-serif' }}>
        Terms of Service
      </h1>
      <p className="text-sm text-[#475569] mb-12">Last updated: {LAST_UPDATED}</p>

      <div className="space-y-10 leading-relaxed">

        <section>
          <h2 className="text-xl font-semibold text-[#F8FAFC] mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using LexLens (&ldquo;Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[#F8FAFC] mb-3">2. Description of Service</h2>
          <p>
            LexLens is an AI-powered contract analysis tool that provides automated risk scoring, clause identification, and plain-English summaries of legal documents. The Service is provided for informational purposes only.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[#F8FAFC] mb-3">3. Not Legal Advice</h2>
          <p className="font-semibold text-amber-400 mb-2">
            LexLens does not provide legal advice.
          </p>
          <p>
            The analysis, risk scores, summaries, and recommendations generated by LexLens are produced by an AI model and are for informational purposes only. They do not constitute legal advice, do not create an attorney-client relationship, and should not be relied upon as a substitute for consultation with a qualified attorney licensed in your jurisdiction.
          </p>
          <p className="mt-3">
            Always consult a qualified attorney before signing any contract or making decisions based on contract analysis.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[#F8FAFC] mb-3">4. User Accounts</h2>
          <p>
            You must create an account to use certain features of the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[#F8FAFC] mb-3">5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 mt-2 space-y-1">
            <li>Upload documents you do not have the right to share</li>
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the Service</li>
            <li>Upload malicious files or attempt to exploit the Service</li>
            <li>Impersonate any person or entity</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[#F8FAFC] mb-3">6. Document Privacy</h2>
          <p>
            Documents you upload are used solely to provide the analysis Service. We do not sell your documents or share them with third parties except as required to operate the Service (e.g., sending text to AI providers for analysis). See our <a href="/privacy" className="text-violet-400 hover:underline">Privacy Policy</a> for details.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[#F8FAFC] mb-3">7. Intellectual Property</h2>
          <p>
            LexLens and its original content, features, and functionality are owned by LexLens and are protected by applicable intellectual property laws. You retain ownership of any documents you upload.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[#F8FAFC] mb-3">8. Disclaimer of Warranties</h2>
          <p>
            THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT AI ANALYSIS RESULTS WILL BE ACCURATE OR COMPLETE.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[#F8FAFC] mb-3">9. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, LEXLENS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE OR RELIANCE ON ANY ANALYSIS PROVIDED.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[#F8FAFC] mb-3">10. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. We will notify users of material changes via email or a prominent notice on the Service. Continued use of the Service after changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[#F8FAFC] mb-3">11. Contact</h2>
          <p>
            For questions about these Terms, contact us at{' '}
            <a href="mailto:support@lexlens.ai" className="text-violet-400 hover:underline">
              support@lexlens.ai
            </a>.
          </p>
        </section>

      </div>
    </div>
  );
}
