import type { Contract } from '@/types/analysis';
import { format } from 'date-fns';

const RISK_COLORS: Record<string, string> = {
  low: '#059669',
  medium: '#D97706',
  high: '#EA580C',
  critical: '#DC2626',
  safe: '#059669',
  caution: '#D97706',
  danger: '#EA580C',
};

export async function generatePDFReport(contract: Contract): Promise<Buffer> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // ── COVER PAGE ──────────────────────────────────────────────
  doc.setFillColor(10, 10, 15);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, pageWidth, 3, 'F');

  doc.setTextColor(248, 250, 252);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text('LexLens', margin, 50);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('See Through Every Contract', margin, 60);

  doc.setDrawColor(30, 30, 45);
  doc.line(margin, 70, pageWidth - margin, 70);

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(248, 250, 252);
  const nameLines = doc.splitTextToSize(contract.filename, contentWidth);
  doc.text(nameLines, margin, 90);

  doc.setFontSize(14);
  doc.setTextColor(148, 163, 184);
  doc.text(contract.contractType, margin, 110);

  // Risk score circle
  const riskColor = RISK_COLORS[contract.riskLevel] ?? '#D97706';
  const [r, g, b] = hexToRgb(riskColor);
  doc.setDrawColor(r, g, b);
  doc.setLineWidth(3);
  doc.circle(pageWidth - margin - 25, 95, 20);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(r, g, b);
  doc.text(String(contract.overallRiskScore), pageWidth - margin - 25, 97, { align: 'center' });
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text('RISK SCORE', pageWidth - margin - 25, 103, { align: 'center' });

  doc.setFontSize(11);
  doc.setTextColor(248, 250, 252);
  doc.text(`Analyzed: ${format(new Date(contract.uploadedAt), 'MMMM d, yyyy')}`, margin, 130);
  doc.text(`Contract Type: ${contract.contractType}`, margin, 140);
  doc.text(`Analyzed by: LexLens AI`, margin, 150);
  doc.text(`Risk Level: ${contract.riskLevel.toUpperCase()}`, margin, 160);

  if (contract.redFlags.length > 0) {
    doc.setFillColor(220, 38, 38, 0.15);
    doc.roundedRect(margin, 175, contentWidth, 25, 3, 3, 'F');
    doc.setFontSize(12);
    doc.setTextColor(220, 38, 38);
    doc.text(`⚠  ${contract.redFlags.length} Red Flag${contract.redFlags.length > 1 ? 's' : ''} Detected`, margin + 5, 190);
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text('Generated by LexLens — Not legal advice. Consult a qualified attorney.', pageWidth / 2, pageHeight - 10, { align: 'center' });

  // ── EXECUTIVE SUMMARY PAGE ──────────────────────────────────
  doc.addPage();
  setPageBackground(doc, pageWidth, pageHeight);
  addPageHeader(doc, pageWidth, margin, 'Executive Summary');

  let y = 50;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(248, 250, 252);
  const summaryLines = doc.splitTextToSize(contract.summary, contentWidth);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 7 + 10;

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(124, 58, 237);
  doc.text('Key Findings', margin, y);
  y += 8;

  contract.keyFindings.forEach((finding) => {
    doc.setFillColor(18, 18, 26);
    doc.roundedRect(margin, y - 5, contentWidth, 14, 2, 2, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(248, 250, 252);
    const lines = doc.splitTextToSize(`• ${finding}`, contentWidth - 10);
    doc.text(lines, margin + 5, y + 3);
    y += lines.length * 7 + 6;
  });

  addPageFooter(doc, pageWidth, pageHeight);

  // ── RED FLAGS PAGE ──────────────────────────────────────────
  if (contract.redFlags.length > 0) {
    doc.addPage();
    setPageBackground(doc, pageWidth, pageHeight);
    addPageHeader(doc, pageWidth, margin, `Red Flags (${contract.redFlags.length})`);
    y = 50;

    contract.redFlags.forEach((flag, i) => {
      if (y > pageHeight - 60) {
        doc.addPage();
        setPageBackground(doc, pageWidth, pageHeight);
        addPageHeader(doc, pageWidth, margin, 'Red Flags (continued)');
        y = 50;
      }

      const flagColor = flag.severity === 'critical' ? [220, 38, 38] : [217, 119, 6];
      doc.setFillColor(flagColor[0], flagColor[1], flagColor[2], 0.1);
      doc.roundedRect(margin, y - 5, contentWidth, 30, 3, 3, 'F');
      doc.setDrawColor(flagColor[0], flagColor[1], flagColor[2]);
      doc.setLineWidth(0.5);
      doc.roundedRect(margin, y - 5, contentWidth, 30, 3, 3, 'S');

      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(flagColor[0], flagColor[1], flagColor[2]);
      doc.text(`${flag.severity.toUpperCase()}: ${flag.title}`, margin + 5, y + 4);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(200, 200, 210);
      const descLines = doc.splitTextToSize(flag.description, contentWidth - 10);
      doc.text(descLines, margin + 5, y + 12);
      y += 40;
    });

    addPageFooter(doc, pageWidth, pageHeight);
  }

  // ── CLAUSE ANALYSIS PAGES ───────────────────────────────────
  const sortedClauses = [...contract.clauses].sort((a, b) => b.riskScore - a.riskScore);

  for (const clause of sortedClauses) {
    doc.addPage();
    setPageBackground(doc, pageWidth, pageHeight);
    addPageHeader(doc, pageWidth, margin, clause.title);
    y = 50;

    const clauseColor = RISK_COLORS[clause.riskLevel] ?? '#D97706';
    const [cr, cg, cb] = hexToRgb(clauseColor);

    // Risk badge
    doc.setFillColor(cr, cg, cb, 0.2);
    doc.roundedRect(margin, y - 5, 60, 10, 2, 2, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(cr, cg, cb);
    doc.text(`${clause.riskLevel.toUpperCase()} — ${clause.riskScore}/100`, margin + 5, y + 2);

    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text(clause.category, pageWidth - margin, y + 2, { align: 'right' });
    y += 18;

    // Original text
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(148, 163, 184);
    doc.text('Original Language:', margin, y);
    y += 7;

    doc.setFillColor(15, 23, 42);
    const origLines = doc.splitTextToSize(clause.originalText, contentWidth - 10);
    const origHeight = origLines.length * 6 + 10;
    doc.roundedRect(margin, y - 3, contentWidth, origHeight, 2, 2, 'F');
    doc.setFontSize(9);
    doc.setFont('courier', 'normal');
    doc.setTextColor(200, 200, 220);
    doc.text(origLines, margin + 5, y + 3);
    y += origHeight + 8;

    // Plain English
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(148, 163, 184);
    doc.text('Plain English:', margin, y);
    y += 7;

    doc.setFillColor(18, 18, 26);
    const plainLines = doc.splitTextToSize(clause.plainEnglish, contentWidth - 10);
    const plainHeight = plainLines.length * 6 + 10;
    doc.roundedRect(margin, y - 3, contentWidth, plainHeight, 2, 2, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(248, 250, 252);
    doc.text(plainLines, margin + 5, y + 3);
    y += plainHeight + 8;

    // Explanation
    if (clause.explanation) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(148, 163, 184);
      doc.text('Why This Matters:', margin, y);
      y += 7;
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(200, 200, 220);
      const expLines = doc.splitTextToSize(clause.explanation, contentWidth);
      doc.text(expLines, margin, y);
      y += expLines.length * 6 + 8;
    }

    // Recommendation
    if (clause.recommendation) {
      doc.setFillColor(5, 150, 105, 0.1);
      const recLines = doc.splitTextToSize(clause.recommendation, contentWidth - 10);
      const recHeight = recLines.length * 6 + 12;
      doc.roundedRect(margin, y - 3, contentWidth, recHeight, 2, 2, 'F');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(5, 150, 105);
      doc.text('Recommendation:', margin + 5, y + 4);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(200, 240, 220);
      doc.text(recLines, margin + 5, y + 11);
    }

    addPageFooter(doc, pageWidth, pageHeight);
  }

  const arrayBuffer = doc.output('arraybuffer');
  return Buffer.from(arrayBuffer);
}

function setPageBackground(doc: any, w: number, h: number) {
  doc.setFillColor(10, 10, 15);
  doc.rect(0, 0, w, h, 'F');
}

function addPageHeader(doc: any, pageWidth: number, margin: number, title: string) {
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, pageWidth, 2, 'F');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text('LEXLENS ANALYSIS REPORT', margin, 12);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(248, 250, 252);
  doc.text(title, margin, 28);
  doc.setDrawColor(30, 30, 45);
  doc.setLineWidth(0.5);
  doc.line(margin, 35, pageWidth - margin, 35);
}

function addPageFooter(doc: any, pageWidth: number, pageHeight: number) {
  doc.setFontSize(7);
  doc.setTextColor(71, 85, 105);
  doc.text(
    'Generated by LexLens — Not legal advice. Consult a qualified attorney.',
    pageWidth / 2,
    pageHeight - 8,
    { align: 'center' }
  );
}

function hexToRgb(hex: string): [number, number, number] {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
    : [124, 58, 237];
}
